[theme]

# Primary accent for interactive elements
primaryColor = '#F7D716'

# Background color for the main content area
backgroundColor = 'black'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#413F42'

# Color used for almost all text
textColor = '#FFFFFF'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "sans serif"
